### ISSUE TITLE
Vertical Face Player Collisions

### ISSUE THREAD

**Issue by CommanderKeef** [GRUFFMAN/Cat-tastrophe_Game#1]
Player tends to collide/stick to vertical faces of objects - can possibly be turned into a gameplay feature.

To reproduce: 
Jump towards a vertical surface

Expected behaviour:
Player should collide without sticking (except possibly when near the top of the object)

**Comment by GRUFFMAN** [comment]
I have fixed this, changes should go live sometime tonight. If it breaks for anyone just reopen but for now I will close.
