### ISSUE TITLE
Crab Rave 10 Hours

### ISSUE THREAD

**Issue by CommanderKeef** [GRUFFMAN/Cat-tastrophe_Game#12]
**Describe the bug**
Crab Rave 10 Hours

**To Reproduce**
1. Go to https://youtu.be/-50NdPawLVY

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by GRUFFMAN** [comment]
Daniel please leave our group alone.

**Comment by CommanderKeef** [comment]
What?

**Comment by CommanderKeef** [comment]
I thought I was part of this group
