### ISSUE TITLE
Scene problems.

### ISSUE THREAD

**Issue by CammyG-114** [GRUFFMAN/Cat-tastrophe_Game#4]
So, for some reason some elements of the game aren't working in the 'level base build' scene. Jumping is shorter, swatting, and Gerald's mechanics are all not really working properly. 

Not sure how we can go about fixing it, and don't know if everyone is having the same problem. Could just be a problem with my computer.

**Comment by CommanderKeef** [comment]
Jumping was changed in my last commit due to being too floaty.

**Comment by CommanderKeef** [comment]
I'm gonna close this and make a separate issue for Gerald as the other problems are fixed.
