### ISSUE TITLE
Grab System Improvements

### ISSUE THREAD

**Issue by CommanderKeef** [GRUFFMAN/Cat-tastrophe_Game#6]
**Describe the bug**
There are a few problems with this system including the following: Grab key needs remapping, moving objects causes them to break too easily, sometimes inaccurate results.

**To Reproduce**
Steps to reproduce the behaviour:
1. Find a moveable object
2. Press the Grab key
3. Try moving the object around

**Expected behaviour**
The object should be possible to move fairly smoothly without breaking unless hit too hard.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 7
 - Ultimate SP1

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
This is related directly in part to collision scripts - I'll look at that myself.

**Comment by GRUFFMAN** [comment]
Feel free to rebind to anything you want, You can replace E for meow, just remember to bind it to something else

**Comment by CommanderKeef** [comment]
This is almost working - everything is fine on the grabbing side - collision script just needs some finesse.

**Comment by GRUFFMAN** [comment]
Closing for now, keys have been rebound and Daniel is no longer working with us.
