### ISSUE TITLE
Menu Interactions Inconsistent

### ISSUE THREAD

**Issue by CommanderKeef** [GRUFFMAN/Cat-tastrophe_Game#9]
**Describe the bug**
Interacting with the in-game menu only works every 2nd attempt.

**To Reproduce**
1. Run the game
2. Press esc to open the pause menu
3. Press any button
4. Repeat steps 1-3

**Expected behavior**
The clicked button should perform its intended function every time.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 7
 - Ultimate SP1

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by GRUFFMAN** [comment]
Will look into

**Comment by GRUFFMAN** [comment]
For reference, the mouse is also locked upon death and on a built version you can't get out of the screen. (I will also try to fix)

**Comment by GRUFFMAN** [comment]
This should be fixed now with the latest update, if anything crops up again reopen :)
